import Footer from "./Components/Footer";
import Header from "./Components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className + " text-gray-800"}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
